require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'my_api_client.gemspec'
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 26

Metrics/MethodLength:
  Max: 12

Metrics/LineLength:
  Max: 100

RSpec/NestedGroups:
  Max: 4
