require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'my_api_client.gemspec'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 4
